name: Update extensions release

on:
  push:

concurrency:
  group: extensions-release
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: print packages
        run: bun pm ls

      - name: build scripts
        run: bunx turbo run build --filter dion*

      - name: Build all extensions
        run: bunx turbo run build

      - name: Build index
        run: |
          bun run build-index

      - name: Ensure release exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: bun .github/scripts/ensureRelease.js extensions extensions

      - name: Clear existing assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: bun .github/scripts/clearAssets.js extensions

      - name: Upload .index contents (no compression)
        env:
          GH_TOKEN: ${{ github.token }}
        run: bun .github/scripts/uploadIndexAssets.js extensions .index
